language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'spotkula-server' ]; then cd .. && eval "mv $currentfolder spotkula-server" && cd spotkula-server; fi
